# -*- coding: utf-8 -*-
"""01_Fundamentos_de_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xbvp_jQ6pXnqsmBHhhakTMCas_kqgVTN

# Python desde cero hasta cientifico de datos

Clase 2 - Fundamentos de python

> Miercoles 13 de septiembre del 2023


Temario para la clase:

*   Comentarios
*   Print
*   Operadores Aritmeticos
*   Variables
*   Tipos de datos
*   Convertir datos de un tipo a otro
*   Input

Realización de los ejercicios:

*   Ejercicio 1
*   Ejercicio 2

## Comentarios

Los comentarios son la manera en que usualmente se dan instrucciones del funcionamiento del código o también para que el mismo desarrollador identifique puntos clave que quiere remarcar.
"""

# Este es un comentario

"""
Este es un comentario
"""

"""## Print

Print es la manera en que se imprime lo que se desea en consola o en el entorno donde se encuentre, print no está ligado a solamente imprimir texto, sino que puede imprimir cualquier cosa que le sea ingresada.
"""

print("Hola mundo")

"""## Operadores aritmeticos



*   Suma
*   Resta
*   Multiplicación
*   División
*   Elevaciones a la n potencia
*   Dividir hasta el entero
*   Resto de la división
"""

print(34 + 32)
print(74 + 23)

print("74" + "23")

print(74 + 23)

# +

print("Suma: ", 50 + 70)

# -
print("Resta: ", 420 - 60)

# *
print("Multiplicación: ", 20 * 30)

# /
print("División: ", 420 / 60)

# Jerarquia de operaciones
print((50 + 20) * 30)

"""## Variables

Una variable es un lugar en la memoria donde se puede almacenar un valor, por ejemplo, un número o una cadena de texto. En Python, las variables se declaran utilizando el nombre de la variable, seguido de un signo igual y el valor que se desea asignar a la variable.
"""

# +=  ----> x = x + 3

x = 10
x += 3

print(f"Suma: {x}")

# -=  ----> x = x - 3
x = 10
x -= 3

print(f"Resta: {x}")

# *=  ----> x = x * 3
x = 10
x *= 3

print(f"Multiplicación: {x}")

# /=  ----> x = x / 3
x = 10
x //= 3

print(f"División: {x}")

# %=  ----> x = x % 3  Resto de la división
x = 10
x %= 3

print(f"Resto de división: {x}")

# //=  ----> x = x // 3 Entero de la división
x = 10
x //= 3

print(f"Entero de una división: {x}")

# **=  ----> x = x ** 3  número elevado a la n potencia
x = 10
x **= 3

print(f"Número elevado a la n potencia: {x}")

"""### Ejercicio 1:

En este desafío, vas a practicar lo que has aprendido acerca de variables en Python. Crea una variable llamada saludo y dentro de esa variable ingresa el saludo que mas te gusta utilizar, luego imprimirlo utilizando la función print.


> Respuestas:


"""

saludo = "kiubo"
print(saludo)

saludo = ("Hola inges")
print(saludo)

saludo = "Hola, buenas nochis"

print(saludo)

#Moises Alejandro Grimaldo Garcia
mi_saludo_personalizado = "Que onda gente"
print(mi_saludo_personalizado)

saludo = "Hola insanos :D"
print(f"{saludo}")

saludo="Bueenas"
print(saludo)

saludo = "Hola, buenas "
print(saludo)

saludo= ("Holi wenas noches")
print(saludo)

saludo= "hola sebas"
print(saludo)

saludo= 'hola sebas'
print(saludo)

saludo = "Buenas noches"
print(saludo)

saludo = "Buen día."
print(saludo)

Saludo= "Hola como estas?"
print(saludo)

saludo='Hola amigibis'
print(saludo)

saludo="Hi"
print(saludo)

saludo = "DestroyPeru"
print(saludo)

saludo = "pelotudo"

Saludo = "hola"

saludo = "buenas"
print(saludo)

saludo = "Hola buenas noches"
print(saludo)

Saludo ="Hola como estas"
print(Saludo)

mi_saludo_insano = "Que onda criaturitas del señor, (asi como dice rubius)"
print(mi_saludo_insano)

saludo = "pelotudo"
print(saludo)

import random

def saludar(nombre):
    if nombre is None:
        nombre = "mundo"

    saludos = ["Hola", "Bienvenido", "Saludos", "¿Cómo estás?", "¿Qué tal?"]
    saludo = saludos[random.randint(0, len(saludos) - 1)]

    print(f"{saludo}, {nombre}!")


saludar("Oscar il basato")

"""## Tipos de datos

*   Números enteros
*   Números de puntos flotantes
*   Texto (Cadena de caracteres) ó strings
*   Booleanos (Verdadero o falso)
*   NULL


"""

print(type(x))
print(type(536))

x = 3.4
print(type(x))

print(type("x"))
print(type('texto'))

mensaje = "Ella dijo: 'Hola'."
print(mensaje)

mensaje = "Ella dijo: \"Hola\"."
print(mensaje)

print(type(True))
print(type(False))

"""## Convertir datos de un tipo a otro"""

print("Número elevado a la n potencia: " + x)

x = str(x)
print("Número elevado a la n potencia: " + x)

x = str(x); print("texto:", x)
x = float(x)
print("decimal:", x)
x = int(x)
print("Entero:", x)

print("""
Este es un string
de multiples
lineas""")

"""### Ejercicio 2:

En este desafío, se busca crear un formato de string que, como resultado, muestre un mensaje el cual deberá tener la siguiente forma:

```
Hola mi nombre es {name}, tengo {age} años y en 10 años tendré {total} años
```


"""

nombre="Eduardo Lazo"
edad=17
total=edad+10

print(f"Hola mi nombre es {nombre}, tengo {edad} años y en 10 años tendré {total} años")

name = ("David")
age = 20
total = age+10

print(f"Hola, mi nombre es {name}. Tengo {age} años y en 10 años tendré {total} años.")

name = "Noé"
age = 21
total = age + 10
print(f"Hola, mi nombre es {name}, tengo {age} años y en 10 años tendré {total} años.")

nombre = "Alonso"
edad = 27

print(f"Hola mi nombre es {nombre}, tengo {edad} y en 10 años tendré {edad+10} xd")

name= "everardo"
edad=21
total=edad+10
print(f"Hola mi nombre es {name}, tengo {edad} años y en 10 años tendré {total} años!")

age = 18
name = "Angel"
total = age + 10

print(f"Hola mi nombre es {name}, tengo {age} años y en 10 años tendré {total} años.")

datos = ["Eric Daniel Puente Ruiz", 19]
print(f"mi nombre es {datos[0]}, tengo {datos[1]} años y en 10 años mas tendre: {datos[1]+10}")

nombre="Joaquin Munir"
edad=18
edad_10=28
print("Mi nombre es ", nombre, " y tengo ", edad, " y en 10 años tendre ", edad_10)

name = "Pablo Pacheco"
age = 69
total = age + 10

print(f'Hola mi nombre es {name} y tengo {age} y en 10 años tendre {total}')

Name = "Max"
edad = 18
ted = 18+10
print("Hola mi nombre es",Name,"Tengo",edad,"años "+"y en 10 años tendre",ted,"años")

#Crear las variables
mi_nombre = "Moises"
mi_edad = 18
age_in_ten_years = 28

#Convertir las variables de int a str
mi_edad = str(mi_edad)
age_in_ten_years = str(age_in_ten_years)

#Imprimir el mensaje concatenando
print(f"hola mi nombre es {mi_nombre} y tengo {mi_edad} años, en 10 años tendre {age_in_ten_years} años")

name = "Leonardo"
age = 17
total = age + 10
print(f"Hola mi nobre es {name}, y tengo {age}, xd")

name = "Leonardo"
age = 17
total = age + 10
print(f"Hola mi nobre es {name}, y tengo {age}, xd")

name= "Arturo"
edad=20
total=edad+20
print(f"Hola mi nombre es {name}, tengo {edad} años y en 20 años tendré {total} años!")

name = "Ricardo"
age = int(18)
total = age + 10
print(f"Hola mi nombre es {name}. Tengo {age} años y en dentro de 10 años tendre {total} años.")

nombre = "Omar Hernández"
edad = 18
total = edad + 10

print(f"Hallo, mein Name ist {nombre}, ich bin {edad} Jahre alt und in 10 Jahren werde ich {total} Jahre alt sein.")

name= "Angel"
edad=19
total=edad+50
print(f"Hola mi nombre es {name}, tengo {edad} años y en 50 años tendré {total} años!")

name = "Luis"
age = 19
total = age + 10
print(f"Hola mi nombre es {name}, tengo {age} y en 10 años tendre {total} años")

name = "Nereyda"
age = 18
total = age + 10

print(f"Hola mi nombre es {name}, tengo {age} años y en 10 años tendré {total} años, si Dios quiere")

name='José Manuel'
age=18
total=age + 10

print(f'Hola mi nombre es {name}, tengo {age} años y en 10 años tendré {total} años')

name = ("Karla")
edad = 23
total= edad + 10
print(f"Hola mi nombre es {name}, tengo {edad} y en 10 años tendré {edad + 10}")

name="sebas"
edad=18
total=18+10
print(f"Hola, mi nombre es {name}, tengo {edad} años y en 10 años tendré {total}")

nombre = "César"
edad = 19
total = age + 10
print(f"Hola mi nombre es {nombre}, tengo {edad} años y en dentro de 10 años tendre {total} años.")

nombre = "Fernando"
age = 29
total = age + 10
print(f"Hola, mi nombre es {name}, tengo {age} años y en 10 años tendré {total} años.")

#segunda actividad
nombre = "Moises"
age = 18
total = age + 10
print(f"Hola, mi nombre es {nombre}, tengo {age} años y en 10 años tendré {total} años.")

"""## Input"""

edad = input("Ingresa tu edad => ")
print(edad)

print(type(edad))

nombre = input("¿Cual es tu nombre?: ")
edad = input("¿Que edad tienes?: ")

edad_num = int(edad)
print(edad_num)

edad

total = edad_num + 10
print(total)

print(f"Tú nombre es {nombre}, tienes {edad} años y en 10 años tendrás {total} años")